// Global variables;
var pageLimit = 20;
var NumberOfPages = 12;
var limit = 20;
var offset = 0;
var arrayOfThumbnails = [];
var imgAttr;
var flagButtons = true;
var flag = false;
var bookmarkedFlag = false;
var bookmarkedHeroesId = [];
var bookmarkedHeroesObj = [];
var currentPage = 0; 
var templateArray = [];
var k = 0;